name: signaling_server
description: WebRTC signaling server
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.3
  dart_firebase_admin: ^0.4.1

dev_dependencies:
  lints: ^3.0.0

